export interface Major {
  id: string;
  name: string;
  nameArabic: string;
  category: string;
  description: string;
  minGPA: number;
  difficulty: "Easy" | "Medium" | "Hard" | "Very Hard";
  duration: string;
  skills: string[];
  subjects: string[];
  pros: string[];
  cons: string[];
  jobOpportunities: string[];
  averageSalary: string;
  similarMajors: string[];
  topUniversities: string[];
  imageQuery: string;
  commonMistakes?: string[];
  demandInIraq?: string;
  demandOutsideIraq?: string;
  demandInIraqLevel?: "Low" | "Medium" | "High";
  demandOutsideIraqLevel?: "Low" | "Medium" | "High";
}

export interface MajorCategory {
  id: string;
  name: string;
  nameArabic: string;
  icon: string;
  link: string;
}

export const categories: MajorCategory[] = [
  {
    id: "all",
    name: "All Majors",
    nameArabic: "جميع التخصصات",
    icon: "📚",
    link: "/browse",
  },
  {
    id: "engineering",
    name: "Engineering",
    nameArabic: "الهندسة",
    icon: "⚙️",
    link: "/browse?category=engineering",
  },
  {
    id: "medicine",
    name: "Medicine & Health",
    nameArabic: "الطب والصحة",
    icon: "🏥",
    link: "/browse?category=medicine",
  },
  {
    id: "science",
    name: "Science",
    nameArabic: "العلوم",
    icon: "🔬",
    link: "/browse?category=science",
  },
  {
    id: "business",
    name: "Business & Economics",
    nameArabic: "الأعمال والاقتصاد",
    icon: "💼",
    link: "/browse?category=business",
  },
  {
    id: "arts",
    name: "Arts & Humanities",
    nameArabic: "الفنون والعلوم الإنسانية",
    icon: "🎨",
    link: "/browse?category=arts",
  },
  {
    id: "IT",
    name: "IT & Computer Science",
    nameArabic: "تكنولوجيا المعلومات",
    icon: "💻",
    link: "/browse?category=IT",
  },
  {
    id: "law",
    name: "Law & Political Science",
    nameArabic: "القانون والعلوم السياسية",
    icon: "⚖️",
    link: "/browse?category=law",
  },
  {
    id: "education",
    name: "Education",
    nameArabic: "التربية",
    icon: "👨‍🏫",
    link: "/browse?category=education",
  },
];

export const majors: Major[] = [
  {
    id: "computer-science",
    name: "Computer Science",
    nameArabic: "علوم الحاسوب",
    category: "IT",
    description:
      "Study of computers, algorithms, programming, and computational systems. Learn to design software, solve complex problems, and innovate in technology.",
    minGPA: 85,
    difficulty: "Hard",
    duration: "4 years",
    skills: [
      "Problem Solving",
      "Logical Thinking",
      "Programming",
      "Mathematics",
      "Creativity",
    ],
    subjects: [
      "Programming",
      "Algorithms",
      "Data Structures",
      "Databases",
      "Networks",
      "AI & Machine Learning",
    ],
    pros: [
      "High salary potential",
      "Many job opportunities",
      "Work remotely",
      "Continuous learning",
      "Innovation",
    ],
    cons: [
      "Requires strong math",
      "Fast-changing field",
      "Long study hours",
      "Can be stressful",
    ],
    jobOpportunities: [
      "Software Developer",
      "Data Scientist",
      "AI Engineer",
      "Mobile App Developer",
      "Cybersecurity Specialist",
      "Game Developer",
    ],
    averageSalary: "$70,000 - $150,000/year",
    similarMajors: [
      "software-engineering",
      "information-technology",
      "data-science",
    ],
    topUniversities: [
      "Baghdad University",
      "University of Technology",
      "Al-Mustansiriya University",
    ],
    imageQuery: "programming code",
    commonMistakes: [
      "Focusing only on coding without understanding fundamentals",
      "Not practicing enough problem-solving",
      "Ignoring mathematics courses",
      "Skipping networking and communication skills",
      "Not building a portfolio of projects",
    ],
    demandInIraq:
      "High demand, especially in Baghdad and Erbil. Tech startups and government digital transformation projects are growing.",
    demandOutsideIraq:
      "Very high global demand. Remote work opportunities with international companies are excellent.",
    demandInIraqLevel: "High",
    demandOutsideIraqLevel: "High",
  },
  {
    id: "medicine",
    name: "Medicine",
    nameArabic: "الطب",
    category: "medicine",
    description:
      "Study human health, diseases, and medical treatments. Become a doctor who diagnoses and treats patients, saving lives every day.",
    minGPA: 95,
    difficulty: "Very Hard",
    duration: "6-7 years",
    skills: [
      "Memorization",
      "Empathy",
      "Communication",
      "Attention to Detail",
      "Stress Management",
    ],
    subjects: [
      "Anatomy",
      "Physiology",
      "Pharmacology",
      "Pathology",
      "Surgery",
      "Clinical Practice",
    ],
    pros: [
      "Noble profession",
      "Help people",
      "Job security",
      "High respect",
      "Good salary",
    ],
    cons: [
      "Very long study duration",
      "Extremely difficult",
      "High stress",
      "Long working hours",
      "Expensive education",
    ],
    jobOpportunities: [
      "General Practitioner",
      "Surgeon",
      "Pediatrician",
      "Cardiologist",
      "Emergency Doctor",
      "Medical Researcher",
    ],
    averageSalary: "$60,000 - $200,000/year",
    similarMajors: ["dentistry", "pharmacy", "nursing"],
    topUniversities: [
      "Baghdad College of Medicine",
      "Basra Medical College",
      "Mosul Medical College",
    ],
    imageQuery: "medical doctor",
    demandInIraqLevel: "High",
    demandOutsideIraqLevel: "High",
  },
  {
    id: "civil-engineering",
    name: "Civil Engineering",
    nameArabic: "الهندسة المدنية",
    category: "engineering",
    description:
      "Design and build infrastructure like roads, bridges, buildings, and water systems. Shape the physical world around us.",
    minGPA: 80,
    difficulty: "Hard",
    duration: "4-5 years",
    skills: [
      "Mathematics",
      "Physics",
      "Problem Solving",
      "Project Management",
      "Creativity",
    ],
    subjects: [
      "Structural Engineering",
      "Construction",
      "Surveying",
      "Hydraulics",
      "Materials Science",
      "AutoCAD",
    ],
    pros: [
      "Build real structures",
      "Job stability",
      "Good salary",
      "Variety of projects",
      "See your impact",
    ],
    cons: [
      "Requires strong math",
      "Site work can be tough",
      "Weather-dependent",
      "Long project timelines",
    ],
    jobOpportunities: [
      "Structural Engineer",
      "Construction Manager",
      "Urban Planner",
      "Highway Engineer",
      "Project Manager",
    ],
    averageSalary: "$55,000 - $110,000/year",
    similarMajors: [
      "architecture",
      "mechanical-engineering",
      "electrical-engineering",
    ],
    topUniversities: [
      "University of Technology - Baghdad",
      "University of Basra",
      "University of Mosul",
    ],
    imageQuery: "civil engineering bridge",
    demandInIraqLevel: "High",
    demandOutsideIraqLevel: "Medium",
  },
  {
    id: "business-administration",
    name: "Business Administration",
    nameArabic: "إدارة الأعمال",
    category: "business",
    description:
      "Learn to manage businesses, make strategic decisions, lead teams, and understand economics and finance.",
    minGPA: 75,
    difficulty: "Medium",
    duration: "4 years",
    skills: [
      "Leadership",
      "Communication",
      "Strategic Thinking",
      "Financial Analysis",
      "Negotiation",
    ],
    subjects: [
      "Management",
      "Marketing",
      "Finance",
      "Economics",
      "Accounting",
      "Business Strategy",
    ],
    pros: [
      "Versatile degree",
      "Entrepreneurship opportunities",
      "Good networking",
      "Many career paths",
      "Transferable skills",
    ],
    cons: [
      "Competitive field",
      "Requires experience",
      "Initial salary may be modest",
      "Broad curriculum",
    ],
    jobOpportunities: [
      "Business Manager",
      "Marketing Manager",
      "Financial Analyst",
      "Entrepreneur",
      "HR Manager",
      "Consultant",
    ],
    averageSalary: "$45,000 - $100,000/year",
    similarMajors: ["economics", "accounting", "marketing"],
    topUniversities: [
      "Baghdad University",
      "Mustansiriya University",
      "Kufa University",
    ],
    imageQuery: "business meeting",
    demandInIraqLevel: "Medium",
    demandOutsideIraqLevel: "Medium",
  },
  {
    id: "electrical-engineering",
    name: "Electrical Engineering",
    nameArabic: "الهندسة الكهربائية",
    category: "engineering",
    description:
      "Study electricity, electronics, and electromagnetism. Design power systems, circuits, and electronic devices.",
    minGPA: 82,
    difficulty: "Hard",
    duration: "4-5 years",
    skills: [
      "Mathematics",
      "Physics",
      "Problem Solving",
      "Circuit Design",
      "Analytical Thinking",
    ],
    subjects: [
      "Circuit Theory",
      "Electronics",
      "Power Systems",
      "Control Systems",
      "Electromagnetic Fields",
      "Digital Systems",
    ],
    pros: [
      "High demand",
      "Good salary",
      "Diverse applications",
      "Innovation opportunities",
      "Job security",
    ],
    cons: [
      "Challenging math and physics",
      "Abstract concepts",
      "Requires precision",
      "Continuous learning",
    ],
    jobOpportunities: [
      "Power Engineer",
      "Electronics Designer",
      "Control Systems Engineer",
      "Telecommunications Engineer",
      "Automation Engineer",
    ],
    averageSalary: "$60,000 - $120,000/year",
    similarMajors: [
      "mechanical-engineering",
      "computer-engineering",
      "civil-engineering",
    ],
    topUniversities: [
      "University of Technology",
      "Baghdad University",
      "Basra University",
    ],
    imageQuery: "electrical circuits",
    demandInIraqLevel: "Medium",
    demandOutsideIraqLevel: "High",
  },
  {
    id: "pharmacy",
    name: "Pharmacy",
    nameArabic: "الصيدلة",
    category: "medicine",
    description:
      "Study medications, their effects, and how to prepare and dispense them. Help people maintain their health through proper medication.",
    minGPA: 88,
    difficulty: "Hard",
    duration: "5 years",
    skills: [
      "Attention to Detail",
      "Chemistry Knowledge",
      "Communication",
      "Patient Care",
      "Memorization",
    ],
    subjects: [
      "Pharmaceutical Chemistry",
      "Pharmacology",
      "Drug Formulation",
      "Clinical Pharmacy",
      "Toxicology",
    ],
    pros: [
      "Help people",
      "Good salary",
      "Job security",
      "Flexible work options",
      "Respected profession",
    ],
    cons: [
      "Long study hours",
      "Memorization heavy",
      "Competitive market",
      "Standing for long hours",
    ],
    jobOpportunities: [
      "Community Pharmacist",
      "Hospital Pharmacist",
      "Clinical Pharmacist",
      "Pharmaceutical Researcher",
      "Drug Inspector",
    ],
    averageSalary: "$50,000 - $100,000/year",
    similarMajors: ["medicine", "chemistry", "nursing"],
    topUniversities: [
      "Baghdad College of Pharmacy",
      "Mustansiriya Pharmacy College",
      "Basra Pharmacy College",
    ],
    imageQuery: "pharmacy medicine",
    demandInIraqLevel: "High",
    demandOutsideIraqLevel: "Medium",
  },
  {
    id: "architecture",
    name: "Architecture",
    nameArabic: "الهندسة المعمارية",
    category: "engineering",
    description:
      "Design buildings and spaces that are beautiful, functional, and sustainable. Combine art with engineering.",
    minGPA: 78,
    difficulty: "Hard",
    duration: "5 years",
    skills: [
      "Creativity",
      "Drawing",
      "Spatial Thinking",
      "Technical Skills",
      "Attention to Detail",
    ],
    subjects: [
      "Architectural Design",
      "Building Technology",
      "History of Architecture",
      "Urban Planning",
      "3D Modeling",
      "Sustainability",
    ],
    pros: [
      "Creative work",
      "See your designs built",
      "Varied projects",
      "Artistic expression",
      "Good income",
    ],
    cons: [
      "Long hours",
      "Demanding clients",
      "Requires both art and math",
      "Competitive field",
    ],
    jobOpportunities: [
      "Architect",
      "Urban Designer",
      "Interior Designer",
      "Landscape Architect",
      "3D Visualization Specialist",
    ],
    averageSalary: "$50,000 - $110,000/year",
    similarMajors: ["civil-engineering", "interior-design", "urban-planning"],
    topUniversities: [
      "University of Technology",
      "Baghdad University",
      "Mosul University",
    ],
    imageQuery: "architecture design",
    demandInIraqLevel: "High",
    demandOutsideIraqLevel: "Medium",
  },
  {
    id: "law",
    name: "Law",
    nameArabic: "القانون",
    category: "law",
    description:
      "Study legal systems, regulations, and justice. Defend rights, practice in courts, and uphold justice.",
    minGPA: 80,
    difficulty: "Hard",
    duration: "4 years",
    skills: [
      "Critical Thinking",
      "Argumentation",
      "Research",
      "Communication",
      "Memory",
    ],
    subjects: [
      "Constitutional Law",
      "Criminal Law",
      "Civil Law",
      "International Law",
      "Legal Writing",
      "Court Procedures",
    ],
    pros: [
      "Prestigious career",
      "Help people",
      "Good salary",
      "Intellectual challenge",
      "Diverse practice areas",
    ],
    cons: [
      "Heavy reading",
      "High pressure",
      "Competitive",
      "Long working hours",
      "Stressful cases",
    ],
    jobOpportunities: [
      "Lawyer",
      "Judge",
      "Legal Advisor",
      "Prosecutor",
      "Legal Researcher",
      "Corporate Counsel",
    ],
    averageSalary: "$40,000 - $150,000/year",
    similarMajors: [
      "political-science",
      "international-relations",
      "criminology",
    ],
    topUniversities: [
      "Baghdad Law College",
      "Nahrain University",
      "Basra Law College",
    ],
    imageQuery: "law justice",
    demandInIraqLevel: "Medium",
    demandOutsideIraqLevel: "Medium",
  },
  {
    id: "dentistry",
    name: "Dentistry",
    nameArabic: "طب الأسنان",
    category: "medicine",
    description:
      "Specialize in oral health, treating teeth, gums, and jaw problems. Help people maintain healthy smiles.",
    minGPA: 90,
    difficulty: "Very Hard",
    duration: "5 years",
    skills: [
      "Manual Dexterity",
      "Attention to Detail",
      "Patient Care",
      "Communication",
      "Precision",
    ],
    subjects: [
      "Oral Anatomy",
      "Dental Materials",
      "Oral Surgery",
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
    ],
    pros: [
      "Good income",
      "Flexible hours",
      "Own practice possible",
      "Help people",
      "Job security",
    ],
    cons: [
      "Expensive education",
      "Physically demanding",
      "Patient anxiety",
      "High responsibility",
    ],
    jobOpportunities: [
      "General Dentist",
      "Orthodontist",
      "Oral Surgeon",
      "Periodontist",
      "Cosmetic Dentist",
    ],
    averageSalary: "$60,000 - $180,000/year",
    similarMajors: ["medicine", "oral-surgery", "pharmacy"],
    topUniversities: [
      "Baghdad Dental College",
      "Mosul Dental College",
      "Basra Dental College",
    ],
    imageQuery: "dentist dental",
    demandInIraqLevel: "High",
    demandOutsideIraqLevel: "High",
  },
  {
    id: "accounting",
    name: "Accounting",
    nameArabic: "المحاسبة",
    category: "business",
    description:
      "Manage financial records, prepare reports, ensure compliance, and help businesses make informed decisions.",
    minGPA: 75,
    difficulty: "Medium",
    duration: "4 years",
    skills: [
      "Attention to Detail",
      "Mathematics",
      "Organization",
      "Analytical Thinking",
      "Ethics",
    ],
    subjects: [
      "Financial Accounting",
      "Managerial Accounting",
      "Auditing",
      "Taxation",
      "Cost Accounting",
      "Financial Analysis",
    ],
    pros: [
      "Job security",
      "Clear career path",
      "Good salary",
      "Every industry needs accountants",
      "Professional certifications",
    ],
    cons: [
      "Can be repetitive",
      "Tax season stress",
      "Requires accuracy",
      "Constant regulation changes",
    ],
    jobOpportunities: [
      "Accountant",
      "Auditor",
      "Tax Consultant",
      "Financial Analyst",
      "Controller",
      "Forensic Accountant",
    ],
    averageSalary: "$45,000 - $95,000/year",
    similarMajors: ["finance", "business-administration", "economics"],
    topUniversities: [
      "Baghdad University",
      "Mustansiriya University",
      "Basra University",
    ],
    imageQuery: "accounting finance",
    demandInIraqLevel: "Medium",
    demandOutsideIraqLevel: "Medium",
  },
  {
    id: "psychology",
    name: "Psychology",
    nameArabic: "علم النفس",
    category: "arts",
    description:
      "Study human behavior, mental processes, and emotional well-being. Help people overcome challenges and improve their lives.",
    minGPA: 72,
    difficulty: "Medium",
    duration: "4 years",
    skills: [
      "Empathy",
      "Active Listening",
      "Critical Thinking",
      "Communication",
      "Observation",
    ],
    subjects: [
      "Developmental Psychology",
      "Abnormal Psychology",
      "Cognitive Psychology",
      "Social Psychology",
      "Research Methods",
      "Counseling",
    ],
    pros: [
      "Help people",
      "Understand human behavior",
      "Diverse career paths",
      "Personal growth",
      "Meaningful work",
    ],
    cons: [
      "Requires graduate degree for practice",
      "Emotionally demanding",
      "Moderate salary initially",
      "Long education path",
    ],
    jobOpportunities: [
      "Clinical Psychologist",
      "Counselor",
      "School Psychologist",
      "HR Specialist",
      "Researcher",
      "Therapist",
    ],
    averageSalary: "$40,000 - $85,000/year",
    similarMajors: ["sociology", "social-work", "education"],
    topUniversities: [
      "Baghdad University",
      "Mustansiriya University",
      "Basra University",
    ],
    imageQuery: "psychology counseling",
    demandInIraqLevel: "Low",
    demandOutsideIraqLevel: "High",
  },
  {
    id: "mechanical-engineering",
    name: "Mechanical Engineering",
    nameArabic: "الهندسة الميكانيكية",
    category: "engineering",
    description:
      "Design, build, and maintain mechanical systems, machines, and engines. Work on everything from cars to spacecraft.",
    minGPA: 80,
    difficulty: "Hard",
    duration: "4-5 years",
    skills: [
      "Mathematics",
      "Physics",
      "Problem Solving",
      "CAD Design",
      "Creativity",
    ],
    subjects: [
      "Thermodynamics",
      "Mechanics",
      "Materials Science",
      "Machine Design",
      "Fluid Mechanics",
      "Manufacturing",
    ],
    pros: [
      "Versatile field",
      "High demand",
      "Good salary",
      "Hands-on work",
      "Innovation opportunities",
    ],
    cons: [
      "Requires strong math",
      "Competitive field",
      "Can be physically demanding",
      "Continuous learning",
    ],
    jobOpportunities: [
      "Mechanical Engineer",
      "Automotive Engineer",
      "Manufacturing Engineer",
      "HVAC Engineer",
      "Aerospace Engineer",
    ],
    averageSalary: "$60,000 - $115,000/year",
    similarMajors: [
      "electrical-engineering",
      "aerospace-engineering",
      "civil-engineering",
    ],
    topUniversities: [
      "University of Technology",
      "Baghdad University",
      "Mosul University",
    ],
    imageQuery: "mechanical engineering",
    demandInIraqLevel: "Medium",
    demandOutsideIraqLevel: "High",
  },
  {
    id: "english-literature",
    name: "English Literature",
    nameArabic: "الأدب الإنجليزي",
    category: "arts",
    description:
      "Study English language, literature, writing, and communication. Analyze texts, develop critical thinking, and master language.",
    minGPA: 70,
    difficulty: "Medium",
    duration: "4 years",
    skills: [
      "Reading",
      "Writing",
      "Critical Analysis",
      "Communication",
      "Creativity",
    ],
    subjects: [
      "Literary Analysis",
      "Poetry",
      "Drama",
      "Creative Writing",
      "Linguistics",
      "Comparative Literature",
    ],
    pros: [
      "Develop strong communication",
      "Improve writing skills",
      "Cultural understanding",
      "Flexible career options",
    ],
    cons: [
      "Competitive job market",
      "May need additional skills",
      "Moderate salary",
      "Limited traditional career paths",
    ],
    jobOpportunities: [
      "Teacher",
      "Translator",
      "Content Writer",
      "Editor",
      "Journalist",
      "Publishing Professional",
    ],
    averageSalary: "$35,000 - $70,000/year",
    similarMajors: ["translation", "journalism", "education"],
    topUniversities: [
      "Baghdad University",
      "Mustansiriya University",
      "Basra University",
    ],
    imageQuery: "literature books",
    demandInIraqLevel: "Low",
    demandOutsideIraqLevel: "Medium",
  },
  {
    id: "nursing",
    name: "Nursing",
    nameArabic: "التمريض",
    category: "medicine",
    description:
      "Provide patient care, assist doctors, and support people through illness and recovery. Be on the frontlines of healthcare.",
    minGPA: 75,
    difficulty: "Medium",
    duration: "4 years",
    skills: [
      "Compassion",
      "Communication",
      "Physical Stamina",
      "Attention to Detail",
      "Stress Management",
    ],
    subjects: [
      "Nursing Fundamentals",
      "Patient Care",
      "Pharmacology",
      "Anatomy & Physiology",
      "Medical-Surgical Nursing",
      "Pediatric Nursing",
    ],
    pros: [
      "Job security",
      "Help people",
      "Good salary",
      "Many specializations",
      "High demand",
    ],
    cons: [
      "Physically demanding",
      "Shift work",
      "Emotionally challenging",
      "High stress",
    ],
    jobOpportunities: [
      "Registered Nurse",
      "ICU Nurse",
      "Pediatric Nurse",
      "Emergency Nurse",
      "Nurse Manager",
      "Surgical Nurse",
    ],
    averageSalary: "$40,000 - $85,000/year",
    similarMajors: ["medicine", "pharmacy", "public-health"],
    topUniversities: [
      "Baghdad Nursing College",
      "Kufa Nursing College",
      "Basra Nursing College",
    ],
    imageQuery: "nursing healthcare",
    demandInIraqLevel: "High",
    demandOutsideIraqLevel: "High",
  },
  {
    id: "information-technology",
    name: "Information Technology",
    nameArabic: "تكنولوجيا المعلومات",
    category: "IT",
    description:
      "Manage computer systems, networks, and technical infrastructure. Keep businesses running smoothly through technology.",
    minGPA: 78,
    difficulty: "Medium",
    duration: "4 years",
    skills: [
      "Technical Skills",
      "Problem Solving",
      "Communication",
      "Troubleshooting",
      "Learning Ability",
    ],
    subjects: [
      "Network Administration",
      "System Administration",
      "Database Management",
      "Cybersecurity",
      "Cloud Computing",
      "IT Support",
    ],
    pros: [
      "High demand",
      "Good salary",
      "Practical skills",
      "Remote work possible",
      "Job security",
    ],
    cons: [
      "Requires constant learning",
      "On-call support",
      "Can be stressful",
      "Certification-heavy",
    ],
    jobOpportunities: [
      "IT Support Specialist",
      "Network Administrator",
      "System Administrator",
      "IT Manager",
      "Cloud Engineer",
      "Security Analyst",
    ],
    averageSalary: "$50,000 - $110,000/year",
    similarMajors: ["computer-science", "cybersecurity", "data-science"],
    topUniversities: [
      "University of Information Technology",
      "Baghdad University",
      "Mosul University",
    ],
    imageQuery: "information technology",
    demandInIraqLevel: "High",
    demandOutsideIraqLevel: "High",
  },
  {
    id: "economics",
    name: "Economics",
    nameArabic: "الاقتصاد",
    category: "business",
    description:
      "Study how societies use resources, make decisions, and understand financial systems, markets, and policies.",
    minGPA: 75,
    difficulty: "Medium",
    duration: "4 years",
    skills: [
      "Analytical Thinking",
      "Mathematics",
      "Statistics",
      "Problem Solving",
      "Research",
    ],
    subjects: [
      "Microeconomics",
      "Macroeconomics",
      "Econometrics",
      "International Economics",
      "Development Economics",
      "Financial Economics",
    ],
    pros: [
      "Versatile degree",
      "Good analytical skills",
      "Policy influence",
      "Good career prospects",
      "Research opportunities",
    ],
    cons: [
      "Requires strong math",
      "Abstract concepts",
      "Competitive field",
      "May need graduate degree",
    ],
    jobOpportunities: [
      "Economist",
      "Financial Analyst",
      "Policy Analyst",
      "Market Researcher",
      "Business Consultant",
      "Data Analyst",
    ],
    averageSalary: "$50,000 - $110,000/year",
    similarMajors: ["business-administration", "finance", "statistics"],
    topUniversities: [
      "Baghdad University",
      "Mustansiriya University",
      "Basra University",
    ],
    imageQuery: "economics finance",
    demandInIraqLevel: "Medium",
    demandOutsideIraqLevel: "Medium",
  },
];
