import type { Metadata } from "next";
import "@/app/_styles/globals.css";
import { Header } from "./_components/Header";
import { Sidebar } from "./_components/SideBar";
import { SidebarProvider } from "./_context/SideBarContext";

export const metadata: Metadata = {
  title: "Major Compass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <Header />
          <Sidebar />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
