import type { Metadata } from "next";
import "@/app/_styles/globals.css";
import { Header } from "./_components/Header";
import { Sidebar } from "./_components/SideBar";
import { SidebarProvider } from "./_context/SideBarContext";
import AnimatedMain from "./_components/AnimateMain";
import { Footer } from "./_components/Footer";
import AIAssistant from "./_components/AIAssistant";

export const metadata: Metadata = {
  title: "Major Compass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50">
        <SidebarProvider>
          <Header />

          <div className="flex">
            <Sidebar />
            <AnimatedMain>
              {children}
              <AIAssistant />
            </AnimatedMain>
          </div>

          <Footer />
        </SidebarProvider>
      </body>
    </html>
  );
}
